///s_literatura(ind_cantico);

if englis {
    switch argument0 {
        case 0: return "This new place exalts my senses, it is gloomy, it carries heaviness, life clings desperate and tired. I see a cemetery to the southwest almost as big as that town to the east, the muddy soil here only grows pumpkin crops to the south. To the north I see a forgotten fort, it seems even the war has abandoned these lands. But don't stink, that decaying human smell causes me to consume life.";
        case 1: return "Stalk mortals, observe their simple lives from beyond the grave, harvest them like a grim reaper. All you can do is let fear flow, I am hunger, I am thirst, I am disease and old age. With ferocity and anger I tear their lives apart and make them mine. Whoever peace falls before my claws is not enough, then his soul will accompany my deadly adventures.";
        case 2: return "Perennial influence of consciousness feeds my stay in the crypt, each passage of time lengthens as long as sleep, a century could last an hour if I neglect the tick tock of outer life, imperishable as an old trauma and fresher than a rotten pharaoh I furrow time, evade the sun, my enemy the sun, rises and greets God. I am for my part what I am, without regrets, without reservations.";
        case 3: return "There are occasions where in the ordinary is the valuable, the ordinary human, his life is an illusory placebo, an extract of luck and strident joy without a future. Others a well of anguish and crying. In the latter there are times I find the valuable, the raw material that forges a wandering and hungry soul, ready to fly through the confines of eternity, Nosferatu.";
        case 4: return "Twisted were the sounds that came from the sisante night, insects flitting under the cloak of darkness, awaited attentively the death of the child. The child with his last strength clung to his desolate mother, looked with dry and red eyes, not understanding how those sunny days of play among the figs, had become dark, forever.";
        case 5: return "The misery in this existence is so multiform that it unfolds across the wide horizon. The memory of the old happiness is the anguish of the present, the agony acclaims the ecstasy of what could have been. The desolate mother hung like withered fruit on a tree, her crying outweighed the flow of her blood. I decided to stoke her misfortune, she now walks at night.";
        case 6: return "Where do I come from? of the past, of the shadow of what I was and of the vital impulse of my unfortunate prey. It is not the first time they have undertaken a hunting campaign against a hunter, nor the last. But those who did it now are dust, and I'm still here. Destroying this borrowed meat only makes me change vehicles, reborn from the ordinary.";
        case 7: return "Day after day hunt to exist, exist to hunt. To exist to keep the memory of a diffuse life, to stoke the desire, desire for power, to be able to circumvent the fateful destiny that concerns each being. To be one is to be the cold and the emptiness, to pursue the unattainable, to stop the dynamism of life by standing firm, hieratic, solemn in the face of changing times.";
        case 8: return "I remember Selene, it is the only valuable thing I remember from yesteryear. Imposing and magnificent under the moon of youthful days, when spring seemed eternally sweet. We were a moment, an instant of the cosmos, being erased by violent destiny. Following decades I woke up of my own free will in limbo, lifeless, without Selene.";
        case 9: return "With no memories beyond suffering, the devils of limbo incessantly gnaw the flesh, torture, seduce. The borrowed body repairs itself but does not rest. Zombies or slaves claiming their being before the archons, others of us spit purity shrouded, we saw that there is behind the curtain, dissatisfied with the light we become monsters.";
        case 10: return "This is my last memory, a final call, the day will frighten the shadows and I will contract with them. More always I will be there, behind you, watching you from the chthonic recesses, from the depths of Hades. When you feel the cold on your neck, breathe out your last breath and see the light at the end of the tunnel, you better not look back.";
    }
}
else {
    switch argument0 {
        case 0: return "Este nuevo lugar exalta mis sentidos, es lúgubre, carga pesadumbre, la vida se aferra desesperada y cansada. Veo un cementerio al suroeste casi tan grande como aquel pueblo al este, el suelo fangoso aquí sólo genera cultivos de calabazas al sur. Al norte veo un olvidado fuerte, parece hasta la guerra ha abandonado estas tierras. Pero no la peste, ese olor a humano decadenteme me provoca consumir vida.";
        case 1: return "Asechar a los mortales, observar sus simples vidas desde la ultratumba, cosecharlas cual parca. Todo lo que pueden hacer es dejar fluir el miedo, soy el hambre, soy la sed, soy la enfermedad y la vejez. Con ferocidad e ira desgarro sus vidas y las hago mías. Quien ante mis garras cae la paz no alcanza, luego su alma acompañará mis mortíferas andanzas.";
        case 2: return "Influjo de consciencia perenne alimenta mi estadía en la cripta, cada paso del tiempo se elonga tanto como el sueño, un siglo podría durar una hora si descuido el tic tac de la vida exterior, imperecedero como un viejo trauma y más fresco que un carcomido faraón surco el tiempo, evado al sol, mi enemigo el sol, se levanta y saluda a dios. Yo soy por mi parte lo que soy, sin remordimientos, sin reservas.";
        case 3: return "Hay ocasiones donde en lo ordinario se halla lo valioso, el humano ordinario, su vida es un ilusorio placebo, un extracto de suerte y estridente alegría sin futuro. Otros un pozo de angustia y llanto. En estos últimos hay veces hallo lo valioso, la materia prima que forja a un alma errante y hambrienta, lista para volar por los confines de la eternidad, Nosferatu.";
        case 4: return "Retorcidos eran los sonidos que provenían de la sisante noche, insectos revoloteando bajo el manto de la oscuridad, esperaba atento la defunción del pequeño. El niño con sus últimas fuerzas se aferraba a su desolada madre, miraba con ojos secos y rojos, sin entender como esos días soleados de juego entre los higos, se habían tornado oscuros, para siempre.";
        case 5: return "Es tan multiforme la desdicha en está existencia, que se despliega por el ancho horizonte. La memoria de la vieja dicha es la angustia del presente, la agonía aclama al éxtasis de lo que pudo ser. La desolada madre colgaba como fruto marchito en un árbol, su llanto superó al caudal de su sangre. Decidí atizar su desgracia, ella ahora camina en la noche.";
        case 6: return "¿De dónde provengo? del pasado, de la sombra de lo que fuí y del impulso vital de mis desafortunadas presas. No es la primera vez que emprenden una campaña de cacería contra un cazador, ni la última. Más los que lo hicieron ahora son polvo, y yo estoy aquí aún. Destruir está carne prestada sólo me hace cambiar de vehículo, renacer desde lo ordinario.";
        case 7: return "Día tras día cazar para existir, existir para cazar. Existir para mantener el recuerdo de una difusa vida, atizar el deseo, deseo por el poder, poder burlar el destino fatídico que atañe a cada ser. Ser uno es ser el frío y el vacío, perseguir lo inalcanzable, frenar el dinamismo de la vida manteniéndose firme, hierático, solemne ante los tiempos cambiantes.";
        case 8: return "Recuerdo a Selene, es lo único valioso que recuerdo de antaño. Imponente y magna bajo la luna de los días juveniles, cuando la primavera parecía eternamente dulce. Éramos un momento, un instante del cosmos, siendo borrado por el violento destino. Décadas siguientes desperté por voluntad propia en un limbo, sin vida, sin Selene.";
        case 9: return "Sin recuerdos más allá del sufrimiento, los diablos del limbo roen la carne incesantemente, torturan, seducen. El cuerpo prestado se repara pero no descansa. Zombies o esclavos reivindicando su ser ante los arcontes, otros escupimos la pureza amortajadas, vimos que hay detrás del telón, insatisfechos con la luz nos tornamos monstruos.";
        case 10: return "Está es mi última memoria, un llamado final, el día espantará a las sombras y yo me contraeré con ellas. Más siempre estaré ahí, tras de tí, observándote desde los recovecos ctónicos, desde lo profundo del Hades. Cuando sientas el frío en el cuello, exhales el último respiro y veas la luz al final del túnel, más vale no mires atrás.";
    }
}
return "";

